typedef sequence<string> EchoList1;
typedef sequence<float> ValueList1;

struct Time1
{
  unsigned long sec;    // sec
  unsigned long nsec;   // nano sec
};

struct TimedState1
{
  Time1 tm;
  short data;
};

interface MyService
{
  EchoList1 get_echo_history();
  ValueList1 get_value_history();
};
