// -*- IDL -*-
#include <SDOPackage.idl>
#include <RTC.idl>

module OpenRTM
{
  enum StatusKind
  {
    COMPONENT_PROFILE,
    RTC_STATUS,
    EC_STATUS,
    PORT_PROFILE,
    CONFIGURATION,
    HEART_BEAT
  };

  interface ComponentObserver
    : SDOPackage::SDOService
  {
    oneway void update_status(in StatusKind status_kind, in string hint);
  };

};
