// -*- IDL -*-
/*!
 * @file OpenRTM.idl
 * @brief OpenRTM interface definition
 * @date $Date: 2007/10/02 10:14:28 $
 * @author Noriaki Ando <n-ando@aist.go.jp>
 *
 * Copyright (C) 2007
 *     Task-intelligence Research Group,
 *     Intelligent Systems Research Institute,
 *     National Institute of
 *         Advanced Industrial Science and Technology (AIST), Japan
 *     All rights reserved.
 *
 * $Id: OpenRTM.idl,v 1.1 2007/10/02 10:14:28 arafune Exp $
 *
 */

/*
 * $Log: OpenRTM.idl,v $
 * Revision 1.1  2007/10/02 10:14:28  arafune
 * *** empty log message ***
 *
 * Revision 1.1  2007/04/13 18:17:59  n-ando
 * OpenRTM specific interface definition.
 *
 */

#include "RTC.idl"

#pragma prefix "openrtm.aist.go.jp"

module OpenRTM
{

  interface FiniteStateMachineComponent
    : RTC::RTObject, RTC::FsmParticipant
  {
  };

  interface DataFlowFiniteStateMachineComponent
    : RTC::RTObject, RTC::DataFlowComponent, RTC::FsmParticipant
  {
  };

  interface DataFlowMultiModeComponent
    : RTC::RTObject, RTC::DataFlowComponent, RTC::MultiModeObject
  {
  };

  interface FiniteStateMachineMultiModeComponent
    : RTC::RTObject, RTC::FsmParticipant, RTC::MultiModeObject
  {
  };

  interface DataFlowFiniteStateMachineMultiModeComponent
    : RTC::RTObject, RTC::DataFlowComponent, RTC::FsmParticipant, RTC::MultiModeObject
  {
  };


  interface ExtTrigExecutionContextService
    : RTC::ExecutionContextService
  {
    oneway void tick();
  };

};
