//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.11.22 at 05:14:48 ŒßŒã JST 
//


package org.openrtp.namespaces.rtc.version02;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for constraint_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="constraint_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="ConstraintHashType" type="{http://www.openrtp.org/namespaces/rtc}constraint_hash_type"/>
 *         &lt;element name="ConstraintListType" type="{http://www.openrtp.org/namespaces/rtc}constraint_list_type"/>
 *         &lt;element name="ConstraintUnitType" type="{http://www.openrtp.org/namespaces/rtc}constraint_unit_type"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "constraint_type", propOrder = {
    "constraintHashType",
    "constraintListType",
    "constraintUnitType"
})
public class ConstraintType {

    @XmlElement(name = "ConstraintHashType")
    protected ConstraintHashType constraintHashType;
    @XmlElement(name = "ConstraintListType")
    protected ConstraintListType constraintListType;
    @XmlElement(name = "ConstraintUnitType")
    protected ConstraintUnitType constraintUnitType;

    /**
     * Gets the value of the constraintHashType property.
     * 
     * @return
     *     possible object is
     *     {@link ConstraintHashType }
     *     
     */
    public ConstraintHashType getConstraintHashType() {
        return constraintHashType;
    }

    /**
     * Sets the value of the constraintHashType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConstraintHashType }
     *     
     */
    public void setConstraintHashType(ConstraintHashType value) {
        this.constraintHashType = value;
    }

    /**
     * Gets the value of the constraintListType property.
     * 
     * @return
     *     possible object is
     *     {@link ConstraintListType }
     *     
     */
    public ConstraintListType getConstraintListType() {
        return constraintListType;
    }

    /**
     * Sets the value of the constraintListType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConstraintListType }
     *     
     */
    public void setConstraintListType(ConstraintListType value) {
        this.constraintListType = value;
    }

    /**
     * Gets the value of the constraintUnitType property.
     * 
     * @return
     *     possible object is
     *     {@link ConstraintUnitType }
     *     
     */
    public ConstraintUnitType getConstraintUnitType() {
        return constraintUnitType;
    }

    /**
     * Sets the value of the constraintUnitType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConstraintUnitType }
     *     
     */
    public void setConstraintUnitType(ConstraintUnitType value) {
        this.constraintUnitType = value;
    }

}
