/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package jp.go.aist.rtm.nameserviceview.model.nameservice.validation;

import jp.go.aist.rtm.nameserviceview.model.nameservice.NameServiceReference;

/**
 * A sample validator interface for {@link jp.go.aist.rtm.nameserviceview.model.nameservice.CorbaNode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CorbaNodeValidator {
	boolean validate();

	boolean validateNameServiceReference(NameServiceReference value);

	boolean validateZombie(boolean value);
}
