/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package jp.go.aist.rtm.nameserviceview.model.nameservice.validation;

import OpenRTMNaming.NamingNotifier;
import org.omg.CosNaming.Binding;
import org.omg.CosNaming.NamingContextExt;

/**
 * A sample validator interface for {@link jp.go.aist.rtm.nameserviceview.model.nameservice.NameServiceReference}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NameServiceReferenceValidator {
	boolean validate();

	boolean validateBinding(Binding value);
	boolean validateNameServerName(String value);
	boolean validateRootNamingContext(NamingContextExt value);

	boolean validateNotifier(NamingNotifier value);

	boolean validateUpdated(boolean value);
}
