//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.01.06 at 10:42:01 午前 JST 
//


package org.openrtp.namespaces.rts.version02;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openrtp.namespaces.rts package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RtsProfile_QNAME = new QName("http://www.openrtp.org/namespaces/rts", "RtsProfile");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openrtp.namespaces.rts
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ComponentGroup }
     * 
     */
    public ComponentGroup createComponentGroup() {
        return new ComponentGroup();
    }

    /**
     * Create an instance of {@link ExecutionContextExt }
     * 
     */
    public ExecutionContextExt createExecutionContextExt() {
        return new ExecutionContextExt();
    }

    /**
     * Create an instance of {@link Activation }
     * 
     */
    public Activation createActivation() {
        return new Activation();
    }

    /**
     * Create an instance of {@link Waittime }
     * 
     */
    public Waittime createWaittime() {
        return new Waittime();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link Participants }
     * 
     */
    public Participants createParticipants() {
        return new Participants();
    }

    /**
     * Create an instance of {@link Preceding }
     * 
     */
    public Preceding createPreceding() {
        return new Preceding();
    }

    /**
     * Create an instance of {@link TargetPort }
     * 
     */
    public TargetPort createTargetPort() {
        return new TargetPort();
    }

    /**
     * Create an instance of {@link Shutdown }
     * 
     */
    public Shutdown createShutdown() {
        return new Shutdown();
    }

    /**
     * Create an instance of {@link Resetting }
     * 
     */
    public Resetting createResetting() {
        return new Resetting();
    }

    /**
     * Create an instance of {@link DataportConnector }
     * 
     */
    public DataportConnector createDataportConnector() {
        return new DataportConnector();
    }

    /**
     * Create an instance of {@link MessageSending }
     * 
     */
    public MessageSending createMessageSending() {
        return new MessageSending();
    }

    /**
     * Create an instance of {@link ServiceportExt }
     * 
     */
    public ServiceportExt createServiceportExt() {
        return new ServiceportExt();
    }

    /**
     * Create an instance of {@link ServiceportConnector }
     * 
     */
    public ServiceportConnector createServiceportConnector() {
        return new ServiceportConnector();
    }

    /**
     * Create an instance of {@link RtsProfile }
     * 
     */
    public RtsProfile createRtsProfile() {
        return new RtsProfile();
    }

    /**
     * Create an instance of {@link RtsProfileExt }
     * 
     */
    public RtsProfileExt createRtsProfileExt() {
        return new RtsProfileExt();
    }

    /**
     * Create an instance of {@link TargetComponent }
     * 
     */
    public TargetComponent createTargetComponent() {
        return new TargetComponent();
    }

    /**
     * Create an instance of {@link ExecutionContext }
     * 
     */
    public ExecutionContext createExecutionContext() {
        return new ExecutionContext();
    }

    /**
     * Create an instance of {@link Condition }
     * 
     */
    public Condition createCondition() {
        return new Condition();
    }

    /**
     * Create an instance of {@link ServiceportConnectorExt }
     * 
     */
    public ServiceportConnectorExt createServiceportConnectorExt() {
        return new ServiceportConnectorExt();
    }

    /**
     * Create an instance of {@link Deactivation }
     * 
     */
    public Deactivation createDeactivation() {
        return new Deactivation();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link ComponentExt }
     * 
     */
    public ComponentExt createComponentExt() {
        return new ComponentExt();
    }

    /**
     * Create an instance of {@link ConfigurationSet }
     * 
     */
    public ConfigurationSet createConfigurationSet() {
        return new ConfigurationSet();
    }

    /**
     * Create an instance of {@link Finalize }
     * 
     */
    public Finalize createFinalize() {
        return new Finalize();
    }

    /**
     * Create an instance of {@link Component }
     * 
     */
    public Component createComponent() {
        return new Component();
    }

    /**
     * Create an instance of {@link DataportExt }
     * 
     */
    public DataportExt createDataportExt() {
        return new DataportExt();
    }

    /**
     * Create an instance of {@link TargetExecutioncontext }
     * 
     */
    public TargetExecutioncontext createTargetExecutioncontext() {
        return new TargetExecutioncontext();
    }

    /**
     * Create an instance of {@link ConfigurationData }
     * 
     */
    public ConfigurationData createConfigurationData() {
        return new ConfigurationData();
    }

    /**
     * Create an instance of {@link Dataport }
     * 
     */
    public Dataport createDataport() {
        return new Dataport();
    }

    /**
     * Create an instance of {@link ConditionExt }
     * 
     */
    public ConditionExt createConditionExt() {
        return new ConditionExt();
    }

    /**
     * Create an instance of {@link TargetComponentExt }
     * 
     */
    public TargetComponentExt createTargetComponentExt() {
        return new TargetComponentExt();
    }

    /**
     * Create an instance of {@link Startup }
     * 
     */
    public Startup createStartup() {
        return new Startup();
    }

    /**
     * Create an instance of {@link Initialize }
     * 
     */
    public Initialize createInitialize() {
        return new Initialize();
    }

    /**
     * Create an instance of {@link TargetPortExt }
     * 
     */
    public TargetPortExt createTargetPortExt() {
        return new TargetPortExt();
    }

    /**
     * Create an instance of {@link DataportConnectorExt }
     * 
     */
    public DataportConnectorExt createDataportConnectorExt() {
        return new DataportConnectorExt();
    }

    /**
     * Create an instance of {@link Serviceport }
     * 
     */
    public Serviceport createServiceport() {
        return new Serviceport();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RtsProfile }{@code >}}
     * RtsProfileExtのインスタンスを返すように手修正 2009.01.06
     */
    @XmlElementDecl(namespace = "http://www.openrtp.org/namespaces/rts", name = "RtsProfile")
    public JAXBElement<RtsProfileExt> createRtsProfile(RtsProfileExt value) {
        return new JAXBElement<RtsProfileExt>(_RtsProfile_QNAME, RtsProfileExt.class, null, value);
    }

}
