//
// Generated by JTB 1.3.2
//

package jp.go.aist.rtm.rtcbuilder.corba.idl.parser.visitor;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.*;
import java.util.*;

/**
 * All GJ visitors with no argument must implement this interface.
 */

public interface GJNoArguVisitor<R> {

   //
   // GJ Auto class visitors with no argument
   //

   public R visit(NodeList n);
   public R visit(NodeListOptional n);
   public R visit(NodeOptional n);
   public R visit(NodeSequence n);
   public R visit(NodeToken n);

   //
   // User-generated visitor methods below
   //

   /**
    * nodeList -> ( definition() )+
    */
   public R visit(specification n);

   /**
    * nodeChoice -> type_dcl() ";"
    *       | const_dcl() ";"
    *       | except_dcl() ";"
    *       | interfacex() ";"
    *       | module() ";"
    */
   public R visit(definition n);

   /**
    * nodeToken -> "module"
    * identifier -> identifier()
    * nodeToken1 -> "{"
    * nodeList -> ( definition() )+
    * nodeToken2 -> "}"
    */
   public R visit(module n);

   /**
    * nodeChoice -> interface_dcl()
    *       | forward_dcl()
    */
   public R visit(interfacex n);

   /**
    * interface_header -> interface_header()
    * nodeToken -> "{"
    * interface_body -> interface_body()
    * nodeToken1 -> "}"
    */
   public R visit(interface_dcl n);

   /**
    * nodeToken -> "interface"
    * identifier -> identifier()
    */
   public R visit(forward_dcl n);

   /**
    * nodeToken -> "interface"
    * identifier -> identifier()
    * nodeOptional -> [ inheritance_spec() ]
    */
   public R visit(interface_header n);

   /**
    * nodeListOptional -> ( export() )*
    */
   public R visit(interface_body n);

   /**
    * nodeChoice -> type_dcl() ";"
    *       | const_dcl() ";"
    *       | except_dcl() ";"
    *       | attr_dcl() ";"
    *       | op_dcl() ";"
    */
   public R visit(export n);

   /**
    * nodeToken -> ":"
    * scoped_name -> scoped_name()
    * nodeListOptional -> ( "," scoped_name() )*
    */
   public R visit(inheritance_spec n);

   /**
    * nodeOptional -> [ "::" ]
    * identifier -> identifier()
    * nodeListOptional -> ( "::" identifier() )*
    */
   public R visit(scoped_name n);

   /**
    * nodeToken -> "const"
    * const_type -> const_type()
    * identifier -> identifier()
    * nodeToken1 -> "="
    * const_exp -> const_exp()
    */
   public R visit(const_dcl n);

   /**
    * nodeChoice -> integer_type()
    *       | char_type()
    *       | boolean_type()
    *       | floating_pt_type()
    *       | string_type()
    *       | scoped_name()
    */
   public R visit(const_type n);

   /**
    * or_expr -> or_expr()
    */
   public R visit(const_exp n);

   /**
    * xor_expr -> xor_expr()
    * nodeListOptional -> ( "|" xor_expr() )*
    */
   public R visit(or_expr n);

   /**
    * and_expr -> and_expr()
    * nodeListOptional -> ( "^" and_expr() )*
    */
   public R visit(xor_expr n);

   /**
    * shift_expr -> shift_expr()
    * nodeListOptional -> ( "&" shift_expr() )*
    */
   public R visit(and_expr n);

   /**
    * add_expr -> add_expr()
    * nodeListOptional -> ( ( ">>" | "<<" ) add_expr() )*
    */
   public R visit(shift_expr n);

   /**
    * mult_expr -> mult_expr()
    * nodeListOptional -> ( ( "+" | "-" ) mult_expr() )*
    */
   public R visit(add_expr n);

   /**
    * unary_expr -> unary_expr()
    * nodeListOptional -> ( ( "*" | "/" | "%" ) unary_expr() )*
    */
   public R visit(mult_expr n);

   /**
    * nodeOptional -> [ unary_operator() ]
    * primary_expr -> primary_expr()
    */
   public R visit(unary_expr n);

   /**
    * nodeChoice -> "-"
    *       | "+"
    *       | "~"
    */
   public R visit(unary_operator n);

   /**
    * nodeChoice -> scoped_name()
    *       | literal()
    *       | "(" const_exp() ")"
    */
   public R visit(primary_expr n);

   /**
    * nodeChoice -> integer_literal()
    *       | string_literal()
    *       | character_literal()
    *       | floating_pt_literal()
    *       | boolean_literal()
    */
   public R visit(literal n);

   /**
    * nodeChoice -> "TRUE"
    *       | "FALSE"
    */
   public R visit(boolean_literal n);

   /**
    * const_exp -> const_exp()
    */
   public R visit(positive_int_const n);

   /**
    * nodeChoice -> "typedef" type_declarator()
    *       | struct_type()
    *       | union_type()
    *       | enum_type()
    */
   public R visit(type_dcl n);

   /**
    * type_spec -> type_spec()
    * declarators -> declarators()
    */
   public R visit(type_declarator n);

   /**
    * nodeChoice -> simple_type_spec()
    *       | constr_type_spec()
    */
   public R visit(type_spec n);

   /**
    * nodeChoice -> base_type_spec()
    *       | template_type_spec()
    *       | scoped_name()
    */
   public R visit(simple_type_spec n);

   /**
    * nodeChoice -> floating_pt_type()
    *       | integer_type()
    *       | char_type()
    *       | boolean_type()
    *       | octet_type()
    *       | any_type()
    */
   public R visit(base_type_spec n);

   /**
    * nodeChoice -> sequence_type()
    *       | string_type()
    */
   public R visit(template_type_spec n);

   /**
    * nodeChoice -> struct_type()
    *       | union_type()
    *       | enum_type()
    */
   public R visit(constr_type_spec n);

   /**
    * declarator -> declarator()
    * nodeListOptional -> ( "," declarator() )*
    */
   public R visit(declarators n);

   /**
    * nodeChoice -> complex_declarator()
    *       | simple_declarator()
    */
   public R visit(declarator n);

   /**
    * identifier -> identifier()
    */
   public R visit(simple_declarator n);

   /**
    * array_declarator -> array_declarator()
    */
   public R visit(complex_declarator n);

   /**
    * nodeChoice -> "float"
    *       | "double"
    */
   public R visit(floating_pt_type n);

   /**
    * nodeChoice -> signed_int()
    *       | unsigned_int()
    */
   public R visit(integer_type n);

   /**
    * nodeChoice -> signed_long_long_int()
    *       | signed_long_double_int()
    *       | signed_long_int()
    *       | signed_short_int()
    */
   public R visit(signed_int n);

   /**
    * nodeToken -> "long"
    */
   public R visit(signed_long_int n);

   /**
    * nodeToken -> "short"
    */
   public R visit(signed_short_int n);

   /**
    * nodeToken -> "long"
    * nodeToken1 -> "long"
    */
   public R visit(signed_long_long_int n);

   /**
    * nodeToken -> "long"
    * nodeToken1 -> "double"
    */
   public R visit(signed_long_double_int n);

   /**
    * nodeChoice -> unsigned_long_long_int()
    *       | unsigned_long_int()
    *       | unsigned_short_int()
    */
   public R visit(unsigned_int n);

   /**
    * nodeToken -> "unsigned"
    * nodeToken1 -> "long"
    */
   public R visit(unsigned_long_int n);

   /**
    * nodeToken -> "unsigned"
    * nodeToken1 -> "short"
    */
   public R visit(unsigned_short_int n);

   /**
    * nodeToken -> "unsigned"
    * nodeToken1 -> "long"
    * nodeToken2 -> "long"
    */
   public R visit(unsigned_long_long_int n);

   /**
    * nodeToken -> "char"
    */
   public R visit(char_type n);

   /**
    * nodeToken -> "boolean"
    */
   public R visit(boolean_type n);

   /**
    * nodeToken -> "octet"
    */
   public R visit(octet_type n);

   /**
    * nodeToken -> "any"
    */
   public R visit(any_type n);

   /**
    * nodeToken -> "struct"
    * identifier -> identifier()
    * nodeToken1 -> "{"
    * member_list -> member_list()
    * nodeToken2 -> "}"
    */
   public R visit(struct_type n);

   /**
    * nodeList -> ( member() )+
    */
   public R visit(member_list n);

   /**
    * type_spec -> type_spec()
    * declarators -> declarators()
    * nodeToken -> ";"
    */
   public R visit(member n);

   /**
    * nodeToken -> "union"
    * identifier -> identifier()
    * nodeToken1 -> "switch"
    * nodeToken2 -> "("
    * switch_type_spec -> switch_type_spec()
    * nodeToken3 -> ")"
    * nodeToken4 -> "{"
    * switch_body -> switch_body()
    * nodeToken5 -> "}"
    */
   public R visit(union_type n);

   /**
    * nodeChoice -> integer_type()
    *       | char_type()
    *       | boolean_type()
    *       | enum_type()
    *       | scoped_name()
    */
   public R visit(switch_type_spec n);

   /**
    * nodeList -> ( casex() )+
    */
   public R visit(switch_body n);

   /**
    * nodeList -> ( case_label() )+
    * element_spec -> element_spec()
    * nodeToken -> ";"
    */
   public R visit(casex n);

   /**
    * nodeChoice -> "case" const_exp() ":"
    *       | "default" ":"
    */
   public R visit(case_label n);

   /**
    * type_spec -> type_spec()
    * declarator -> declarator()
    */
   public R visit(element_spec n);

   /**
    * nodeToken -> "enum"
    * identifier -> identifier()
    * nodeToken1 -> "{"
    * enumerator -> enumerator()
    * nodeListOptional -> ( "," enumerator() )*
    * nodeToken2 -> "}"
    */
   public R visit(enum_type n);

   /**
    * identifier -> identifier()
    */
   public R visit(enumerator n);

   /**
    * nodeToken -> "sequence"
    * nodeToken1 -> "<"
    * simple_type_spec -> simple_type_spec()
    * nodeOptional -> [ "," positive_int_const() ]
    * nodeToken2 -> ">"
    */
   public R visit(sequence_type n);

   /**
    * nodeToken -> "string"
    * nodeOptional -> [ "<" positive_int_const() ">" ]
    */
   public R visit(string_type n);

   /**
    * identifier -> identifier()
    * nodeList -> ( fixed_array_size() )+
    */
   public R visit(array_declarator n);

   /**
    * nodeToken -> "["
    * positive_int_const -> positive_int_const()
    * nodeToken1 -> "]"
    */
   public R visit(fixed_array_size n);

   /**
    * nodeOptional -> [ "readonly" ]
    * nodeToken -> "attribute"
    * param_type_spec -> param_type_spec()
    * simple_declarator -> simple_declarator()
    * nodeListOptional -> ( "," simple_declarator() )*
    */
   public R visit(attr_dcl n);

   /**
    * nodeToken -> "exception"
    * identifier -> identifier()
    * nodeOptional -> ( "{" )?
    * nodeListOptional -> ( member() | "exception_body" )*
    * nodeOptional1 -> ( "}" )?
    */
   public R visit(except_dcl n);

   /**
    * nodeOptional -> [ op_attribute() ]
    * op_type_spec -> op_type_spec()
    * identifier -> identifier()
    * parameter_dcls -> parameter_dcls()
    * nodeOptional1 -> [ raises_expr() ]
    * nodeOptional2 -> [ context_expr() ]
    */
   public R visit(op_dcl n);

   /**
    * nodeToken -> "oneway"
    */
   public R visit(op_attribute n);

   /**
    * nodeChoice -> param_type_spec()
    *       | "void"
    */
   public R visit(op_type_spec n);

   /**
    * nodeToken -> "("
    * nodeOptional -> [ param_dcl() ( "," param_dcl() )* ]
    * nodeToken1 -> ")"
    */
   public R visit(parameter_dcls n);

   /**
    * param_attribute -> param_attribute()
    * param_type_spec -> param_type_spec()
    * simple_declarator -> simple_declarator()
    */
   public R visit(param_dcl n);

   /**
    * nodeChoice -> "in"
    *       | "out"
    *       | "inout"
    */
   public R visit(param_attribute n);

   /**
    * nodeToken -> "raises"
    * nodeToken1 -> "("
    * scoped_name -> scoped_name()
    * nodeListOptional -> ( "," scoped_name() )*
    * nodeToken2 -> ")"
    */
   public R visit(raises_expr n);

   /**
    * nodeToken -> "context"
    * nodeToken1 -> "("
    * string_literal -> string_literal()
    * nodeListOptional -> ( "," string_literal() )*
    * nodeToken2 -> ")"
    */
   public R visit(context_expr n);

   /**
    * nodeChoice -> base_type_spec()
    *       | string_type()
    *       | scoped_name()
    */
   public R visit(param_type_spec n);

   /**
    * nodeToken -> <ID>
    */
   public R visit(identifier n);

   /**
    * nodeChoice -> <OCTALINT>
    *       | <DECIMALINT>
    *       | <HEXADECIMALINT>
    */
   public R visit(integer_literal n);

   /**
    * nodeToken -> <STRING>
    */
   public R visit(string_literal n);

   /**
    * nodeToken -> <CHARACTER>
    */
   public R visit(character_literal n);

   /**
    * nodeChoice -> <FLOATONE>
    *       | <FLOATTWO>
    */
   public R visit(floating_pt_literal n);

}

