//
// Generated by JTB 1.3.2
//

package jp.go.aist.rtm.rtcbuilder.corba.idl.parser.visitor;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.*;
import java.util.*;

/**
 * All GJ void visitors must implement this interface.
 */

public interface GJVoidVisitor<A> {

   //
   // GJ void Auto class visitors
   //

   public void visit(NodeList n, A argu);
   public void visit(NodeListOptional n, A argu);
   public void visit(NodeOptional n, A argu);
   public void visit(NodeSequence n, A argu);
   public void visit(NodeToken n, A argu);

   //
   // User-generated visitor methods below
   //

   /**
    * nodeList -> ( definition() )+
    */
   public void visit(specification n, A argu);

   /**
    * nodeChoice -> type_dcl() ";"
    *       | const_dcl() ";"
    *       | except_dcl() ";"
    *       | interfacex() ";"
    *       | module() ";"
    */
   public void visit(definition n, A argu);

   /**
    * nodeToken -> "module"
    * identifier -> identifier()
    * nodeToken1 -> "{"
    * nodeList -> ( definition() )+
    * nodeToken2 -> "}"
    */
   public void visit(module n, A argu);

   /**
    * nodeChoice -> interface_dcl()
    *       | forward_dcl()
    */
   public void visit(interfacex n, A argu);

   /**
    * interface_header -> interface_header()
    * nodeToken -> "{"
    * interface_body -> interface_body()
    * nodeToken1 -> "}"
    */
   public void visit(interface_dcl n, A argu);

   /**
    * nodeToken -> "interface"
    * identifier -> identifier()
    */
   public void visit(forward_dcl n, A argu);

   /**
    * nodeToken -> "interface"
    * identifier -> identifier()
    * nodeOptional -> [ inheritance_spec() ]
    */
   public void visit(interface_header n, A argu);

   /**
    * nodeListOptional -> ( export() )*
    */
   public void visit(interface_body n, A argu);

   /**
    * nodeChoice -> type_dcl() ";"
    *       | const_dcl() ";"
    *       | except_dcl() ";"
    *       | attr_dcl() ";"
    *       | op_dcl() ";"
    */
   public void visit(export n, A argu);

   /**
    * nodeToken -> ":"
    * scoped_name -> scoped_name()
    * nodeListOptional -> ( "," scoped_name() )*
    */
   public void visit(inheritance_spec n, A argu);

   /**
    * nodeOptional -> [ "::" ]
    * identifier -> identifier()
    * nodeListOptional -> ( "::" identifier() )*
    */
   public void visit(scoped_name n, A argu);

   /**
    * nodeToken -> "const"
    * const_type -> const_type()
    * identifier -> identifier()
    * nodeToken1 -> "="
    * const_exp -> const_exp()
    */
   public void visit(const_dcl n, A argu);

   /**
    * nodeChoice -> integer_type()
    *       | char_type()
    *       | boolean_type()
    *       | floating_pt_type()
    *       | string_type()
    *       | scoped_name()
    */
   public void visit(const_type n, A argu);

   /**
    * or_expr -> or_expr()
    */
   public void visit(const_exp n, A argu);

   /**
    * xor_expr -> xor_expr()
    * nodeListOptional -> ( "|" xor_expr() )*
    */
   public void visit(or_expr n, A argu);

   /**
    * and_expr -> and_expr()
    * nodeListOptional -> ( "^" and_expr() )*
    */
   public void visit(xor_expr n, A argu);

   /**
    * shift_expr -> shift_expr()
    * nodeListOptional -> ( "&" shift_expr() )*
    */
   public void visit(and_expr n, A argu);

   /**
    * add_expr -> add_expr()
    * nodeListOptional -> ( ( ">>" | "<<" ) add_expr() )*
    */
   public void visit(shift_expr n, A argu);

   /**
    * mult_expr -> mult_expr()
    * nodeListOptional -> ( ( "+" | "-" ) mult_expr() )*
    */
   public void visit(add_expr n, A argu);

   /**
    * unary_expr -> unary_expr()
    * nodeListOptional -> ( ( "*" | "/" | "%" ) unary_expr() )*
    */
   public void visit(mult_expr n, A argu);

   /**
    * nodeOptional -> [ unary_operator() ]
    * primary_expr -> primary_expr()
    */
   public void visit(unary_expr n, A argu);

   /**
    * nodeChoice -> "-"
    *       | "+"
    *       | "~"
    */
   public void visit(unary_operator n, A argu);

   /**
    * nodeChoice -> scoped_name()
    *       | literal()
    *       | "(" const_exp() ")"
    */
   public void visit(primary_expr n, A argu);

   /**
    * nodeChoice -> integer_literal()
    *       | string_literal()
    *       | character_literal()
    *       | floating_pt_literal()
    *       | boolean_literal()
    */
   public void visit(literal n, A argu);

   /**
    * nodeChoice -> "TRUE"
    *       | "FALSE"
    */
   public void visit(boolean_literal n, A argu);

   /**
    * const_exp -> const_exp()
    */
   public void visit(positive_int_const n, A argu);

   /**
    * nodeChoice -> "typedef" type_declarator()
    *       | struct_type()
    *       | union_type()
    *       | enum_type()
    */
   public void visit(type_dcl n, A argu);

   /**
    * type_spec -> type_spec()
    * declarators -> declarators()
    */
   public void visit(type_declarator n, A argu);

   /**
    * nodeChoice -> simple_type_spec()
    *       | constr_type_spec()
    */
   public void visit(type_spec n, A argu);

   /**
    * nodeChoice -> base_type_spec()
    *       | template_type_spec()
    *       | scoped_name()
    */
   public void visit(simple_type_spec n, A argu);

   /**
    * nodeChoice -> floating_pt_type()
    *       | integer_type()
    *       | char_type()
    *       | boolean_type()
    *       | octet_type()
    *       | any_type()
    */
   public void visit(base_type_spec n, A argu);

   /**
    * nodeChoice -> sequence_type()
    *       | string_type()
    */
   public void visit(template_type_spec n, A argu);

   /**
    * nodeChoice -> struct_type()
    *       | union_type()
    *       | enum_type()
    */
   public void visit(constr_type_spec n, A argu);

   /**
    * declarator -> declarator()
    * nodeListOptional -> ( "," declarator() )*
    */
   public void visit(declarators n, A argu);

   /**
    * nodeChoice -> complex_declarator()
    *       | simple_declarator()
    */
   public void visit(declarator n, A argu);

   /**
    * identifier -> identifier()
    */
   public void visit(simple_declarator n, A argu);

   /**
    * array_declarator -> array_declarator()
    */
   public void visit(complex_declarator n, A argu);

   /**
    * nodeChoice -> "float"
    *       | "double"
    */
   public void visit(floating_pt_type n, A argu);

   /**
    * nodeChoice -> signed_int()
    *       | unsigned_int()
    */
   public void visit(integer_type n, A argu);

   /**
    * nodeChoice -> signed_long_long_int()
    *       | signed_long_double_int()
    *       | signed_long_int()
    *       | signed_short_int()
    */
   public void visit(signed_int n, A argu);

   /**
    * nodeToken -> "long"
    */
   public void visit(signed_long_int n, A argu);

   /**
    * nodeToken -> "short"
    */
   public void visit(signed_short_int n, A argu);

   /**
    * nodeToken -> "long"
    * nodeToken1 -> "long"
    */
   public void visit(signed_long_long_int n, A argu);

   /**
    * nodeToken -> "long"
    * nodeToken1 -> "double"
    */
   public void visit(signed_long_double_int n, A argu);

   /**
    * nodeChoice -> unsigned_long_long_int()
    *       | unsigned_long_int()
    *       | unsigned_short_int()
    */
   public void visit(unsigned_int n, A argu);

   /**
    * nodeToken -> "unsigned"
    * nodeToken1 -> "long"
    */
   public void visit(unsigned_long_int n, A argu);

   /**
    * nodeToken -> "unsigned"
    * nodeToken1 -> "short"
    */
   public void visit(unsigned_short_int n, A argu);

   /**
    * nodeToken -> "unsigned"
    * nodeToken1 -> "long"
    * nodeToken2 -> "long"
    */
   public void visit(unsigned_long_long_int n, A argu);

   /**
    * nodeToken -> "char"
    */
   public void visit(char_type n, A argu);

   /**
    * nodeToken -> "boolean"
    */
   public void visit(boolean_type n, A argu);

   /**
    * nodeToken -> "octet"
    */
   public void visit(octet_type n, A argu);

   /**
    * nodeToken -> "any"
    */
   public void visit(any_type n, A argu);

   /**
    * nodeToken -> "struct"
    * identifier -> identifier()
    * nodeToken1 -> "{"
    * member_list -> member_list()
    * nodeToken2 -> "}"
    */
   public void visit(struct_type n, A argu);

   /**
    * nodeList -> ( member() )+
    */
   public void visit(member_list n, A argu);

   /**
    * type_spec -> type_spec()
    * declarators -> declarators()
    * nodeToken -> ";"
    */
   public void visit(member n, A argu);

   /**
    * nodeToken -> "union"
    * identifier -> identifier()
    * nodeToken1 -> "switch"
    * nodeToken2 -> "("
    * switch_type_spec -> switch_type_spec()
    * nodeToken3 -> ")"
    * nodeToken4 -> "{"
    * switch_body -> switch_body()
    * nodeToken5 -> "}"
    */
   public void visit(union_type n, A argu);

   /**
    * nodeChoice -> integer_type()
    *       | char_type()
    *       | boolean_type()
    *       | enum_type()
    *       | scoped_name()
    */
   public void visit(switch_type_spec n, A argu);

   /**
    * nodeList -> ( casex() )+
    */
   public void visit(switch_body n, A argu);

   /**
    * nodeList -> ( case_label() )+
    * element_spec -> element_spec()
    * nodeToken -> ";"
    */
   public void visit(casex n, A argu);

   /**
    * nodeChoice -> "case" const_exp() ":"
    *       | "default" ":"
    */
   public void visit(case_label n, A argu);

   /**
    * type_spec -> type_spec()
    * declarator -> declarator()
    */
   public void visit(element_spec n, A argu);

   /**
    * nodeToken -> "enum"
    * identifier -> identifier()
    * nodeToken1 -> "{"
    * enumerator -> enumerator()
    * nodeListOptional -> ( "," enumerator() )*
    * nodeToken2 -> "}"
    */
   public void visit(enum_type n, A argu);

   /**
    * identifier -> identifier()
    */
   public void visit(enumerator n, A argu);

   /**
    * nodeToken -> "sequence"
    * nodeToken1 -> "<"
    * simple_type_spec -> simple_type_spec()
    * nodeOptional -> [ "," positive_int_const() ]
    * nodeToken2 -> ">"
    */
   public void visit(sequence_type n, A argu);

   /**
    * nodeToken -> "string"
    * nodeOptional -> [ "<" positive_int_const() ">" ]
    */
   public void visit(string_type n, A argu);

   /**
    * identifier -> identifier()
    * nodeList -> ( fixed_array_size() )+
    */
   public void visit(array_declarator n, A argu);

   /**
    * nodeToken -> "["
    * positive_int_const -> positive_int_const()
    * nodeToken1 -> "]"
    */
   public void visit(fixed_array_size n, A argu);

   /**
    * nodeOptional -> [ "readonly" ]
    * nodeToken -> "attribute"
    * param_type_spec -> param_type_spec()
    * simple_declarator -> simple_declarator()
    * nodeListOptional -> ( "," simple_declarator() )*
    */
   public void visit(attr_dcl n, A argu);

   /**
    * nodeToken -> "exception"
    * identifier -> identifier()
    * nodeOptional -> ( "{" )?
    * nodeListOptional -> ( member() | "exception_body" )*
    * nodeOptional1 -> ( "}" )?
    */
   public void visit(except_dcl n, A argu);

   /**
    * nodeOptional -> [ op_attribute() ]
    * op_type_spec -> op_type_spec()
    * identifier -> identifier()
    * parameter_dcls -> parameter_dcls()
    * nodeOptional1 -> [ raises_expr() ]
    * nodeOptional2 -> [ context_expr() ]
    */
   public void visit(op_dcl n, A argu);

   /**
    * nodeToken -> "oneway"
    */
   public void visit(op_attribute n, A argu);

   /**
    * nodeChoice -> param_type_spec()
    *       | "void"
    */
   public void visit(op_type_spec n, A argu);

   /**
    * nodeToken -> "("
    * nodeOptional -> [ param_dcl() ( "," param_dcl() )* ]
    * nodeToken1 -> ")"
    */
   public void visit(parameter_dcls n, A argu);

   /**
    * param_attribute -> param_attribute()
    * param_type_spec -> param_type_spec()
    * simple_declarator -> simple_declarator()
    */
   public void visit(param_dcl n, A argu);

   /**
    * nodeChoice -> "in"
    *       | "out"
    *       | "inout"
    */
   public void visit(param_attribute n, A argu);

   /**
    * nodeToken -> "raises"
    * nodeToken1 -> "("
    * scoped_name -> scoped_name()
    * nodeListOptional -> ( "," scoped_name() )*
    * nodeToken2 -> ")"
    */
   public void visit(raises_expr n, A argu);

   /**
    * nodeToken -> "context"
    * nodeToken1 -> "("
    * string_literal -> string_literal()
    * nodeListOptional -> ( "," string_literal() )*
    * nodeToken2 -> ")"
    */
   public void visit(context_expr n, A argu);

   /**
    * nodeChoice -> base_type_spec()
    *       | string_type()
    *       | scoped_name()
    */
   public void visit(param_type_spec n, A argu);

   /**
    * nodeToken -> <ID>
    */
   public void visit(identifier n, A argu);

   /**
    * nodeChoice -> <OCTALINT>
    *       | <DECIMALINT>
    *       | <HEXADECIMALINT>
    */
   public void visit(integer_literal n, A argu);

   /**
    * nodeToken -> <STRING>
    */
   public void visit(string_literal n, A argu);

   /**
    * nodeToken -> <CHARACTER>
    */
   public void visit(character_literal n, A argu);

   /**
    * nodeChoice -> <FLOATONE>
    *       | <FLOATTWO>
    */
   public void visit(floating_pt_literal n, A argu);

}

