//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.24 at 04:33:50 ŒßŒã JST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.openrtp.org/namespaces/rts", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.openrtp.namespaces.rts.version02;
