package jp.go.aist.rtm.toolscommon.model.component.validation;


import RTC.ComponentProfile;
import RTC.ExecutionContextService;
import RTC.ExecutionContext;
import _SDOPackage.Configuration;
import _SDOPackage.Organization;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link jp.go.aist.rtm.toolscommon.model.component.CorbaComponent}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CorbaComponentValidator {
	boolean validate();

	boolean validateExecutionContextState(int value);
	boolean validateComponentState(int value);
	boolean validateSDOConfiguration(Configuration value);
	boolean validateRTCComponentProfile(ComponentProfile value);
	boolean validateRTCExecutionContexts(EList<ExecutionContextService> value);

	boolean validateRTCParticipationContexts(EList<ExecutionContext> value);

	boolean validateRTCParticipatingContexts(EList<ExecutionContext> value);

	boolean validateRTCExecutionContext(EList<ExecutionContext> value);
	boolean validateSDOOrganization(Organization value);
	boolean validateIor(String value);
}