package jp.go.aist.rtm.toolscommon.model.component.validation;


import jp.go.aist.rtm.toolscommon.model.component.Component;
import jp.go.aist.rtm.toolscommon.model.component.SystemDiagram;
import jp.go.aist.rtm.toolscommon.model.component.SystemDiagramKind;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link jp.go.aist.rtm.toolscommon.model.component.SystemDiagram}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SystemDiagramValidator {
	boolean validate();

	boolean validateComponents(EList<Component> value);
	boolean validateKind(SystemDiagramKind value);
	boolean validateConnectorProcessing(boolean value);
	boolean validateSystemId(String value);
	boolean validateCreationDate(String value);
	boolean validateUpdateDate(String value);
	boolean validateParentSystemDiagram(SystemDiagram value);
	boolean validateCompositeComponent(Component value);
}