module RTC {
module RTM {
	struct Time
	{
		unsigned long sec;    // sec
		unsigned long nsec;   // nano sec
	};

	interface MyService
	{
		Time echo(in Time msg, in string str);
	};
};
};
