<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="manager"
    nsURI="http:///jp/go/aist/rtm/nameserviceview/model/manager.ecore" nsPrefix="jp.go.aist.rtm.nameserviceview.model.manager">
  <eClassifiers xsi:type="ecore:EClass" name="NameServerManager" eSuperTypes="#//Node">
    <eOperations name="refreshAll"/>
    <eOperations name="isExist" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="nameServer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="addNameServer" eType="#//NameServerContext">
      <eParameters name="nameServer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="setSynchronizeInterval">
      <eParameters name="milliSecond" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NameServerContext" eSuperTypes="#//Node">
    <eOperations name="synchronizeLocal"/>
    <eOperations name="finalizeLocal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameServerName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="../../jp.go.aist.rtm.toolscommon/src/jp/go/aist/rtm/toolscommon/model/core.ecore#//WrapperObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//Node" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
