/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package jp.go.aist.rtm.toolscommon.model.manager.validation;

import RTC.ComponentProfile;
import RTM.ManagerProfile;

import RTM.ModuleProfile;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link jp.go.aist.rtm.toolscommon.model.manager.RTCManager}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RTCManagerValidator {
	boolean validate();

	boolean validateManagerProfile(ManagerProfile value);
	boolean validateInstanceNameL(String value);
	boolean validatePathId(String value);
	boolean validateComponentProfiles(EList value);
	boolean validateLoadableModuleProfiles(EList value);
	boolean validateLoadedModuleProfiles(EList value);
	boolean validateFactoryModuleProfiles(EList value);
}
