//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.11.22 at 05:14:48 ŒßŒã JST 
//


package org.openrtp.namespaces.rtc.version02;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for constraint_unit_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="constraint_unit_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Not" type="{http://www.openrtp.org/namespaces/rtc}not"/>
 *         &lt;element name="And" type="{http://www.openrtp.org/namespaces/rtc}and"/>
 *         &lt;element name="Or" type="{http://www.openrtp.org/namespaces/rtc}or"/>
 *         &lt;element name="propertyIsNullType" type="{http://www.openrtp.org/namespaces/rtc}property_is_null_type"/>
 *         &lt;element name="propertyIsEqualTo" type="{http://www.openrtp.org/namespaces/rtc}property_is_equal_to"/>
 *         &lt;element name="propertyIsNotEqualTo" type="{http://www.openrtp.org/namespaces/rtc}property_is_not_equal_to"/>
 *         &lt;element name="propertyIsLessThan" type="{http://www.openrtp.org/namespaces/rtc}property_is_less_than"/>
 *         &lt;element name="propertyIsGreaterThan" type="{http://www.openrtp.org/namespaces/rtc}property_is_greater_than"/>
 *         &lt;element name="propertyIsLessThanOrEqualTo" type="{http://www.openrtp.org/namespaces/rtc}property_is_less_than_or_equal_to"/>
 *         &lt;element name="propertyIsGreaterThanOrEqualTo" type="{http://www.openrtp.org/namespaces/rtc}property_is_greater_than_or_equal_to"/>
 *         &lt;element name="propertyIsLike" type="{http://www.openrtp.org/namespaces/rtc}property_is_like"/>
 *         &lt;element name="propertyIsBetween" type="{http://www.openrtp.org/namespaces/rtc}property_is_between"/>
 *       &lt;/choice>
 *       &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "constraint_unit_type", propOrder = {
    "not",
    "and",
    "or",
    "propertyIsNullType",
    "propertyIsEqualTo",
    "propertyIsNotEqualTo",
    "propertyIsLessThan",
    "propertyIsGreaterThan",
    "propertyIsLessThanOrEqualTo",
    "propertyIsGreaterThanOrEqualTo",
    "propertyIsLike",
    "propertyIsBetween"
})
public class ConstraintUnitType {

    @XmlElement(name = "Not")
    protected Not not;
    @XmlElement(name = "And")
    protected And and;
    @XmlElement(name = "Or")
    protected Or or;
    protected PropertyIsNullType propertyIsNullType;
    protected PropertyIsEqualTo propertyIsEqualTo;
    protected PropertyIsNotEqualTo propertyIsNotEqualTo;
    protected PropertyIsLessThan propertyIsLessThan;
    protected PropertyIsGreaterThan propertyIsGreaterThan;
    protected PropertyIsLessThanOrEqualTo propertyIsLessThanOrEqualTo;
    protected PropertyIsGreaterThanOrEqualTo propertyIsGreaterThanOrEqualTo;
    protected PropertyIsLike propertyIsLike;
    protected PropertyIsBetween propertyIsBetween;
    @XmlAttribute(namespace = "http://www.openrtp.org/namespaces/rtc")
    protected String key;

    /**
     * Gets the value of the not property.
     * 
     * @return
     *     possible object is
     *     {@link Not }
     *     
     */
    public Not getNot() {
        return not;
    }

    /**
     * Sets the value of the not property.
     * 
     * @param value
     *     allowed object is
     *     {@link Not }
     *     
     */
    public void setNot(Not value) {
        this.not = value;
    }

    /**
     * Gets the value of the and property.
     * 
     * @return
     *     possible object is
     *     {@link And }
     *     
     */
    public And getAnd() {
        return and;
    }

    /**
     * Sets the value of the and property.
     * 
     * @param value
     *     allowed object is
     *     {@link And }
     *     
     */
    public void setAnd(And value) {
        this.and = value;
    }

    /**
     * Gets the value of the or property.
     * 
     * @return
     *     possible object is
     *     {@link Or }
     *     
     */
    public Or getOr() {
        return or;
    }

    /**
     * Sets the value of the or property.
     * 
     * @param value
     *     allowed object is
     *     {@link Or }
     *     
     */
    public void setOr(Or value) {
        this.or = value;
    }

    /**
     * Gets the value of the propertyIsNullType property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyIsNullType }
     *     
     */
    public PropertyIsNullType getPropertyIsNullType() {
        return propertyIsNullType;
    }

    /**
     * Sets the value of the propertyIsNullType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyIsNullType }
     *     
     */
    public void setPropertyIsNullType(PropertyIsNullType value) {
        this.propertyIsNullType = value;
    }

    /**
     * Gets the value of the propertyIsEqualTo property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyIsEqualTo }
     *     
     */
    public PropertyIsEqualTo getPropertyIsEqualTo() {
        return propertyIsEqualTo;
    }

    /**
     * Sets the value of the propertyIsEqualTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyIsEqualTo }
     *     
     */
    public void setPropertyIsEqualTo(PropertyIsEqualTo value) {
        this.propertyIsEqualTo = value;
    }

    /**
     * Gets the value of the propertyIsNotEqualTo property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyIsNotEqualTo }
     *     
     */
    public PropertyIsNotEqualTo getPropertyIsNotEqualTo() {
        return propertyIsNotEqualTo;
    }

    /**
     * Sets the value of the propertyIsNotEqualTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyIsNotEqualTo }
     *     
     */
    public void setPropertyIsNotEqualTo(PropertyIsNotEqualTo value) {
        this.propertyIsNotEqualTo = value;
    }

    /**
     * Gets the value of the propertyIsLessThan property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyIsLessThan }
     *     
     */
    public PropertyIsLessThan getPropertyIsLessThan() {
        return propertyIsLessThan;
    }

    /**
     * Sets the value of the propertyIsLessThan property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyIsLessThan }
     *     
     */
    public void setPropertyIsLessThan(PropertyIsLessThan value) {
        this.propertyIsLessThan = value;
    }

    /**
     * Gets the value of the propertyIsGreaterThan property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyIsGreaterThan }
     *     
     */
    public PropertyIsGreaterThan getPropertyIsGreaterThan() {
        return propertyIsGreaterThan;
    }

    /**
     * Sets the value of the propertyIsGreaterThan property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyIsGreaterThan }
     *     
     */
    public void setPropertyIsGreaterThan(PropertyIsGreaterThan value) {
        this.propertyIsGreaterThan = value;
    }

    /**
     * Gets the value of the propertyIsLessThanOrEqualTo property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyIsLessThanOrEqualTo }
     *     
     */
    public PropertyIsLessThanOrEqualTo getPropertyIsLessThanOrEqualTo() {
        return propertyIsLessThanOrEqualTo;
    }

    /**
     * Sets the value of the propertyIsLessThanOrEqualTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyIsLessThanOrEqualTo }
     *     
     */
    public void setPropertyIsLessThanOrEqualTo(PropertyIsLessThanOrEqualTo value) {
        this.propertyIsLessThanOrEqualTo = value;
    }

    /**
     * Gets the value of the propertyIsGreaterThanOrEqualTo property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyIsGreaterThanOrEqualTo }
     *     
     */
    public PropertyIsGreaterThanOrEqualTo getPropertyIsGreaterThanOrEqualTo() {
        return propertyIsGreaterThanOrEqualTo;
    }

    /**
     * Sets the value of the propertyIsGreaterThanOrEqualTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyIsGreaterThanOrEqualTo }
     *     
     */
    public void setPropertyIsGreaterThanOrEqualTo(PropertyIsGreaterThanOrEqualTo value) {
        this.propertyIsGreaterThanOrEqualTo = value;
    }

    /**
     * Gets the value of the propertyIsLike property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyIsLike }
     *     
     */
    public PropertyIsLike getPropertyIsLike() {
        return propertyIsLike;
    }

    /**
     * Sets the value of the propertyIsLike property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyIsLike }
     *     
     */
    public void setPropertyIsLike(PropertyIsLike value) {
        this.propertyIsLike = value;
    }

    /**
     * Gets the value of the propertyIsBetween property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyIsBetween }
     *     
     */
    public PropertyIsBetween getPropertyIsBetween() {
        return propertyIsBetween;
    }

    /**
     * Sets the value of the propertyIsBetween property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyIsBetween }
     *     
     */
    public void setPropertyIsBetween(PropertyIsBetween value) {
        this.propertyIsBetween = value;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

}
