package jp.go.aist.rtm.rtcbuilder.corba.idl.parser;
/* Generated By:JavaCC: Do not edit this line. IDLParserConstants.java */
public interface IDLParserConstants {

  int EOF = 0;
  int ID = 69;
  int OCTALINT = 70;
  int DECIMALINT = 71;
  int HEXADECIMALINT = 72;
  int FLOATONE = 73;
  int FLOATTWO = 74;
  int CHARACTER = 75;
  int STRING = 76;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<token of kind 7>",
    "<token of kind 8>",
    "<token of kind 9>",
    "<token of kind 10>",
    "\";\"",
    "\"module\"",
    "\"{\"",
    "\"}\"",
    "\"interface\"",
    "\":\"",
    "\",\"",
    "\"::\"",
    "\"const\"",
    "\"=\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\">>\"",
    "\"<<\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"~\"",
    "\"(\"",
    "\")\"",
    "\"TRUE\"",
    "\"FALSE\"",
    "\"typedef\"",
    "\"float\"",
    "\"double\"",
    "\"long\"",
    "\"short\"",
    "\"unsigned\"",
    "\"char\"",
    "\"boolean\"",
    "\"octet\"",
    "\"any\"",
    "\"struct\"",
    "\"union\"",
    "\"switch\"",
    "\"case\"",
    "\"default\"",
    "\"enum\"",
    "\"sequence\"",
    "\"<\"",
    "\">\"",
    "\"string\"",
    "\"[\"",
    "\"]\"",
    "\"readonly\"",
    "\"attribute\"",
    "\"exception\"",
    "\"exception_body\"",
    "\"oneway\"",
    "\"void\"",
    "\"in\"",
    "\"out\"",
    "\"inout\"",
    "\"raises\"",
    "\"context\"",
    "<ID>",
    "<OCTALINT>",
    "<DECIMALINT>",
    "<HEXADECIMALINT>",
    "<FLOATONE>",
    "<FLOATTWO>",
    "<CHARACTER>",
    "<STRING>",
  };

}
