<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="manager"
    nsURI="http:///jp/go/aist/rtm/toolscommon/model/manager.ecore" nsPrefix="jp.go.aist.rtm.toolscommon.model.manager">
  <eClassifiers xsi:type="ecore:EClass" name="RTCManager" eSuperTypes="core.ecore#//CorbaWrapperObject">
    <eOperations name="getProfileR" eType="#//RTMManagerProfile"/>
    <eOperations name="createComponentR" eType="ecore:EClass component.ecore#//Component">
      <eParameters name="compName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="deleteComponentR" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eParameters name="instanceName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getComponentsR" upperBound="-1" eType="ecore:EDataType component.ecore#//RTCRTObject"/>
    <eOperations name="getComponentProfilesR" upperBound="-1" eType="ecore:EDataType component.ecore#//RTCComponentProfile"/>
    <eOperations name="loadModuleR" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eParameters name="pathname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="initfunc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="unloadModuleR" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eParameters name="pathname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getLoadableModuleProfilesR" upperBound="-1" eType="#//RTMModuleProfile"/>
    <eOperations name="getLoadedModuleProfilesR" upperBound="-1" eType="#//RTMModuleProfile"/>
    <eOperations name="getFactoryModuleProfilesR" upperBound="-1" eType="#//RTMModuleProfile"/>
    <eOperations name="forkR" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="shutdownR" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="getComponentInstanceNamesR" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getLoadableModuleFileNamesR" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getLoadedModuleFileNamesR" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getFactoryProfileTypeNamesR" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getComponentInstanceNames" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getLoadableModuleFileNames" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getLoadedModuleFileNames" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getFactoryTypeNames" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="managerProfile" eType="#//RTMManagerProfile"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instanceNameL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pathId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="componentProfiles" upperBound="-1"
        eType="ecore:EDataType component.ecore#//RTCComponentProfile" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="loadableModuleProfiles"
        upperBound="-1" eType="#//RTMModuleProfile" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="loadedModuleProfiles" upperBound="-1"
        eType="#//RTMModuleProfile" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="factoryModuleProfiles"
        upperBound="-1" eType="#//RTMModuleProfile" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="RTMManagerProfile" instanceClassName="RTM.ManagerProfile"/>
  <eClassifiers xsi:type="ecore:EDataType" name="RTMModuleProfile" instanceClassName="RTM.ModuleProfile"/>
</ecore:EPackage>
