<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="nameservice"
    nsURI="http:///jp/go/aist/rtm/nameserviceview/model/nameserviceview.ecore" nsPrefix="jp.go.aist.rtm.nameserviceview.model.nameservice">
  <eClassifiers xsi:type="ecore:EClass" name="NamingContextNode" eSuperTypes="#//CorbaNode manager.ecore#//NameServerContext">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zombie" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamingObjectNode" eSuperTypes="#//CorbaNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entry" eType="ecore:EClass core.ecore#//WrapperObject"
        resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CorbaNode" eSuperTypes="core.ecore#//CorbaWrapperObject manager.ecore#//Node">
    <eOperations name="deleteR" eExceptions="#//NotFound #//CannotProceed #//InvalidName"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nameServiceReference" eType="#//NameServiceReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamingContext" instanceClassName="org.omg.CosNaming.NamingContext"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="NameServiceReference">
    <eOperations name="createMergedNameServiceReference" eType="#//NameServiceReference">
      <eParameters name="childBinding" eType="#//Binding"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="binding" eType="#//Binding"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameServerName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rootNamingContext" eType="#//NamingContextExt"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="NamingContextExt" instanceClassName="org.omg.CosNaming.NamingContextExt"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Binding" instanceClassName="org.omg.CosNaming.Binding"/>
  <eClassifiers xsi:type="ecore:EDataType" name="NotFound" instanceClassName="org.omg.CosNaming.NamingContextPackage.NotFound"/>
  <eClassifiers xsi:type="ecore:EDataType" name="CannotProceed" instanceClassName="org.omg.CosNaming.NamingContextPackage.CannotProceed"/>
  <eClassifiers xsi:type="ecore:EDataType" name="InvalidName" instanceClassName="org.omg.CosNaming.NamingContextPackage.InvalidName"/>
</ecore:EPackage>
