package jp.go.aist.rtm.toolscommon.model.component.validation;


import jp.go.aist.rtm.toolscommon.model.component.ConnectorProfile;
import jp.go.aist.rtm.toolscommon.model.component.Port;
import jp.go.aist.rtm.toolscommon.model.core.Point;
import org.eclipse.emf.common.util.EMap;

/**
 * A sample validator interface for {@link jp.go.aist.rtm.toolscommon.model.component.PortConnector}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PortConnectorValidator {
	boolean validate();

	boolean validateConnectorProfile(ConnectorProfile value);
	boolean validateRoutingConstraint(EMap<Integer, Point> value);
	boolean validateSource(Port value);
	boolean validateTarget(Port value);
}